### ISSUE TITLE
Which key shoud i use?

### ISSUE THREAD

**Issue by renato04** [zeit/cosmosdb-server#5]
Hi!

When i use `test key` as my dummy key I'm getting encode error, but when i use a valid key like emulator key the connection is refused.

I'm using python to test the connection.

Thanks in advance

**Comment by nkzawa** [comment]
It doesn't check the master key, so I think there is another problem. Can you share the code and/or error logs if possible?

**Comment by renato04** [comment]
Hello!

Here it is my code

```
from pydocumentdb import document_client

client = document_client.DocumentClient(
    'https://localhost:3000/', {'masterKey': 'test key'})

print("creating database")
db = client.CreateDatabase({'id': 'test_database'})

print("creating collection")
collection = client.CreateCollection(
    db['_self'], {'id': 'my_collection'})

input()

```

And here it is the exception log

```
C:\Users\Renato\repos\bliive-api-python\venv\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 51549 --file C:/Users/Renato/repos/bliive-api-python/api_local.py
pydev debugger: process 20748 is connecting

Connected to pydev debugger (build 191.7479.30)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1758, in <module>
creating database
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Renato/repos/bliive-api-python/api_local.py", line 7, in <module>
    db = client.CreateDatabase({'id': 'test_database'})
  File "C:\Users\Renato\repos\bliive-api-python\venv\lib\site-packages\pydocumentdb\document_client.py", line 213, in CreateDatabase
    return self.Create(database, path, 'dbs', None, None, options)
  File "C:\Users\Renato\repos\bliive-api-python\venv\lib\site-packages\pydocumentdb\document_client.py", line 2130, in Create
    options)
  File "C:\Users\Renato\repos\bliive-api-python\venv\lib\site-packages\pydocumentdb\base.py", line 168, in GetHeaders
    headers)
  File "C:\Users\Renato\repos\bliive-api-python\venv\lib\site-packages\pydocumentdb\auth.py", line 56, in GetAuthorizationHeader
    document_client.master_key)
  File "C:\Users\Renato\repos\bliive-api-python\venv\lib\site-packages\pydocumentdb\auth.py", line 85, in __GetAuthorizationTokenUsingMasterKey
    key = base64.b64decode(master_key)
  File "C:\Python36\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

Thanks

**Comment by renato04** [comment]
I put no key and it worked

`client = document_client.DocumentClient(
    'https://localhost:3000/', {'masterKey': ''})`

Thank you @nkzawa
