### ISSUE TITLE
Throws when comparing documents

### ISSUE THREAD

**Issue by arunoda** [zeit/cosmosdb-server#8]
This is a SQL query I'm looking at:

```
SELECT * FROM c WHERE c.foo.bar = "xyz"
```

In this collection we have some documents with `foo` field and for some other's it's `undefined`.

Then when we ran this query, client give us an error and the server reports this:

```
TypeError: Cannot read property 'bar' of undefined
    at $h.paginate.$h.sort.$c.reduce.filter (eval at exports.default (/data/zeit/api/services/cosmos-local/node_modules/@zeit/cosmosdb-query/lib/executor.js:8:21), <anonymous>:8:83)
    at Array.filter (<anonymous>)
    at eval (eval at exports.default (/data/zeit/api/services/cosmos-local/node_modules/@zeit/cosmosdb-query/lib/executor.js:8:21), <anonymous>:6:15)
    at Object.exports.default (/data/zeit/api/services/cosmos-local/node_modules/@zeit/cosmosdb-query/lib/executor.js:13:12)
    at Query.exec (/data/zeit/api/services/cosmos-local/node_modules/@zeit/cosmosdb-query/lib/index.js:29:34)
    at Documents.query (/data/zeit/api/services/cosmos-local/node_modules/@zeit/cosmosdb-server/lib/account/items.js:53:55)
    at _read_items_1.default (/data/zeit/api/services/cosmos-local/node_modules/@zeit/cosmosdb-server/lib/handler/query-documents.js:24:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by nkzawa** [comment]
Fixed by https://github.com/zeit/cosmosdb-query/commit/ee7c6fdbb0ddc224ac7cbd627250e5883afd9bd9 and released as 0.2.4
